spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/matna_db?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        default_batch_fetch_size: 1000
  data:
    redis:
      port: 6379
      host: localhost

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

#로깅 - 배포시 삭제
decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j